name: "example: passport"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Set up JDK 1.11
    uses: actions/setup-java@v1
    with:
      java-version: 1.11
    - name: Checkout zkStrata compiler 
      uses: actions/checkout@v2
    - name: Build zkStrata compiler
      run: |
        mvn -B package --file pom.xml
        cp target/zkstratac.jar zkstratac.jar
    - name: Install rustc nightly 2019-10-26
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2019-10-26
        override: true
    - name: Checkout bulletproofs_gadgets
      uses: actions/checkout@v2
      with:
        repository: MarcKloter/bulletproofs_gadgets
        path: bulletproofs_gadgets
    - name: Build bulletproofs_gadgets
      run: |
        cd bulletproofs_gadgets
        cargo build --release
        cp target/release/prover ./../prover
        cp target/release/verifier ./../verifier
    - name: Prepare example
      run: cp examples/passport/* .
    - name: "Prover: Compile zkStrata statement"
      run: java -jar zkstratac.jar --statement passport-example.zkstrata --schema passport_ch=passport_ch.schema.json --witness-data myPassport=myPassport.json --instance-data myPassport=myPassport.metadata.json 
    - name: "Prover: Generate Zero-Knowledge Proof"
      run: ./prover passport-example
    - name: "Verifier: compile zkStrata statement"
      run: java -jar zkstratac.jar --statement passport-example.zkstrata --schema passport_ch=passport_ch.schema.json --instance-data myPassport=myPassport.metadata.json 
    - name: "Verifier: Verify Zero-Knowledge Proof"
      run: ./verifier passport-example
    - name: Check signature
      run: openssl rsautl -verify -inkey public.pem -pubin -keyform PEM -in signature.crt
